#!/bin/bash
#SBATCH --job-name="copy_whales"
#SBATCH -A fnrpredator
#SBATCH -t 04:00:00
#SBATCH -N 1
#SBATCH -n 64
#SBATCH -e %x_%j.err
#SBATCH -o %x-%j.out
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=allen715@purdue.edu

# a script to recursively find reads (fastq.gz files) and copy to new directory 
find /scratch/bell/allen715/Gray_whales_anna/ -type f -iname '*.fastq.gz' -exec cp {} /scratch/bell/allen715/Gray_whales/Reads/ \;
